Fix the path of embed source maps
oat-sa/grunt-tao-bundle pull request #9
Opened 2019-12-17 14:07 UTC by IgorSalevan

Related to: https://oat-sa.atlassian.net/browse/TDR-7

Added a fix which prepends CSS source-maps with their relative paths.

Companion PR:
https://github.com/oat-sa/extension-tao-itemqti/pull/1366

2019-12-18 15:57 UTC, krampstudio requested changes
That's good but can you please  : 
  - add a test for the resolver ? 
 - give detailed test instructions 
 - the sourcemap path is replaced by an alias instead of the path in some situation, we should resolve them (the matching alias/path is available at https://github.com/oat-sa/grunt-tao-bundle/blob/master/lib/bundler.js#L58)

2019-12-18 15:57 UTC, krampstudio commented on lib/sourceMapPathResolve.js
> +const matchAllSourceMaps = source => {
The rule is to use arrow function in the following situations : 
 - increase readability (one line) 
 - prevent a closure or binding the lexical scope 

So in this case, we prefer using plain function : 
 ```
function matchAllSourceMaps(source) {
```

2019-12-18 15:57 UTC, krampstudio commented on lib/transformer.js
> +
You forgot to remove that part

2019-12-18 15:57 UTC, krampstudio commented on lib/sourceMapPathResolve.js
> + * @param {Object} paths
can you explain what are those paths ?

2019-12-18 15:57 UTC, krampstudio commented on lib/sourceMapPathResolve.js
> +    for (const i in matchedSourceMaps) {
If `matchedSourceMaps` is an array I prefer the iteration to be made using `for ... of ` or `.forEach` (since for ... in doesn't guarantee the index order)

2019-12-18 15:57 UTC, krampstudio commented on lib/sourceMapPathResolve.js
> +        const matchResult = (new RegExp(`css!([\\w|\\-|.|\\/]+)/${matchedSourceMaps[i].file}([\\.css|\\'\\"])`))
why do you need the parenthesis around the RegExp ?

2019-12-19 08:44 UTC, IgorSalevan commented on lib/sourceMapPathResolve.js
> + * @param {Object} paths
added a comment to the `paths` param

2019-12-19 08:46 UTC, IgorSalevan commented on lib/sourceMapPathResolve.js
> +    for (const i in matchedSourceMaps) {
Yes I know that index order maybe not preserved. But changed the implementation and used forEach and got rid of the index.

2019-12-19 08:51 UTC, IgorSalevan commented on lib/sourceMapPathResolve.js
> +        const matchResult = (new RegExp(`css!([\\w|\\-|.|\\/]+)/${matchedSourceMaps[i].file}([\\.css|\\'\\"])`))
Just to surround the dynamic creation of object which is chained then with its method.
Removed.

2019-12-19 08:52 UTC, IgorSalevan commented on lib/sourceMapPathResolve.js
> +const matchAllSourceMaps = source => {
applied your recommendation about the arrow funcs.

2019-12-23 08:51 UTC, krampstudio requested changes

2019-12-23 08:51 UTC, krampstudio commented on lib/sourceMapPathResolve.js
> +                    }
can you please remove this block

2019-12-23 08:58 UTC, krampstudio commented
can you also add a line in the README release history

2019-12-23 09:27 UTC, IgorSalevan commented on lib/sourceMapPathResolve.js
> +                    }
Done.

2019-12-23 09:42 UTC, krampstudio approved these changes

2019-12-23 09:47 UTC, merged